# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'

inhibit_all_warnings!
use_frameworks!

workspace 'ProjectX.xcworkspace'

def shared_UI_pods
  pod 'SkeletonView'
end

def shared_core_pods
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Apollo', '~> 0.27.0'
  pod 'SwiftDate'
  pod 'CocoaLumberjack/Swift'
  pod 'Alamofire'
  pod 'Nuke'
end

# Common modules
target 'Core' do
  project 'Common/Core/Core'
  shared_core_pods
  target 'CoreTests' do
  end
end

target 'ABExperiment' do
  project 'Common/ABExperiment/ABExperiment'
  shared_core_pods
  target 'ABExperimentTests' do
  end
end

target 'DesignSystem' do
  project 'Common/DesignSystem/DesignSystem'
  shared_core_pods
  shared_UI_pods
  target 'DesignSystemTests' do
  end
end

target 'Utils' do
  project 'Common/Utils/Utils'
  shared_core_pods
end

# Feature modules
target 'Map' do
  project 'Features/Map/Map'
  shared_core_pods
end

target 'FoursquareCore' do
  project 'Features/Shared/FoursquareCore/FoursquareCore'
  shared_core_pods
  target 'FoursquareCoreTests' do
  end
end

target 'VenueDetails' do
  project 'Features/VenueDetails/VenueDetails'
  shared_core_pods
  target 'VenueDetailsTests' do
  end
end

# Apps
target 'ProjectX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectX
  shared_core_pods
  shared_UI_pods

  target 'ProjectXTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

